/*
 * PagarMe.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using PagarMe.Standard;
using PagarMe.Standard.Utilities;

namespace PagarMe.Standard.Models
{
    class GetTransactionResponseCreationConverter : JsonCreationConverter<GetTransactionResponse>
    {
        public GetTransactionResponseCreationConverter()
        {
            typeName = "transaction_type";
            dic = new System.Collections.Generic.Dictionary<string, System.Type>()
            {
                { "bank_transfer",typeof(GetBankTransferTransactionResponse)},
                { "safetypay",typeof(GetSafetyPayTransactionResponse)},
                { "voucher",typeof(GetVoucherTransactionResponse)},
                { "boleto",typeof(GetBoletoTransactionResponse)},
                { "debit_card",typeof(GetDebitCardTransactionResponse)},
                { "private_label",typeof(GetPrivateLabelTransactionResponse)},
                { "cash",typeof(GetCashTransactionResponse)},
                { "credit_card",typeof(GetCreditCardTransactionResponse)},
                { "pix",typeof(GetPixTransactionResponse)},
            };
        }
    }
}