/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace PagarmeAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum AccountType
    {
        CONTA_CORRENTE, //TODO: Write general description for this method
        CONTA_POUPANCA, //TODO: Write general description for this method
        CONTA_CORRENTE_CONJUNTA, //TODO: Write general description for this method
        CONTA_POUPANCA_CONJUNTA, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type AccountType
    /// </summary>
    public static class AccountTypeHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "conta_corrente", "conta_poupanca", "conta_corrente_conjunta", "conta_poupanca_conjunta" };

        /// <summary>
        /// Converts a AccountType value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The AccountType value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(AccountType enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case AccountType.CONTA_CORRENTE:
                case AccountType.CONTA_POUPANCA:
                case AccountType.CONTA_CORRENTE_CONJUNTA:
                case AccountType.CONTA_POUPANCA_CONJUNTA:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of AccountType values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of AccountType values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<AccountType> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into AccountType value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed AccountType value</returns>
        public static AccountType ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type AccountType", value));

            return (AccountType) index;
        }
    }
} 