/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class Address : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string country;
        private string state;
        private string city;
        private string neighborhood;
        private string street;
        private string streetNumber;
        private string zipcode;
        private int? id;

        /// <summary>
        /// Obrigatório. País. Duas letras minúsculas. Deve seguir o padão ISO 3166-1 alpha-2
        /// </summary>
        [JsonProperty("country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// Obrigatório. Estado
        /// </summary>
        [JsonProperty("state")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// Obrigatório. Cidade
        /// </summary>
        [JsonProperty("city")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// Bairro
        /// </summary>
        [JsonProperty("neighborhood")]
        public string Neighborhood 
        { 
            get 
            {
                return this.neighborhood; 
            } 
            set 
            {
                this.neighborhood = value;
                onPropertyChanged("Neighborhood");
            }
        }

        /// <summary>
        /// Obrigatório. Rua
        /// </summary>
        [JsonProperty("street")]
        public string Street 
        { 
            get 
            {
                return this.street; 
            } 
            set 
            {
                this.street = value;
                onPropertyChanged("Street");
            }
        }

        /// <summary>
        /// Obrigatório. Número
        /// </summary>
        [JsonProperty("street_number")]
        public string StreetNumber 
        { 
            get 
            {
                return this.streetNumber; 
            } 
            set 
            {
                this.streetNumber = value;
                onPropertyChanged("StreetNumber");
            }
        }

        /// <summary>
        /// Obrigatório. CEP. Para endereço brasileiro, deve conter uma numeração de 8 dígitos
        /// </summary>
        [JsonProperty("zipcode")]
        public string Zipcode 
        { 
            get 
            {
                return this.zipcode; 
            } 
            set 
            {
                this.zipcode = value;
                onPropertyChanged("Zipcode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }
    }
} 