/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class BankAccount : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string bankCode;
        private string agencia;
        private string agenciaDv;
        private string conta;
        private string type;
        private string contaDv;
        private string documentNumber;
        private string legalName;
        private bool chargeTransferFees;
        private DateTime? dateCreated;
        private string pixKey;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bank_code")]
        public string BankCode 
        { 
            get 
            {
                return this.bankCode; 
            } 
            set 
            {
                this.bankCode = value;
                onPropertyChanged("BankCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("agencia")]
        public string Agencia 
        { 
            get 
            {
                return this.agencia; 
            } 
            set 
            {
                this.agencia = value;
                onPropertyChanged("Agencia");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("agencia_dv")]
        public string AgenciaDv 
        { 
            get 
            {
                return this.agenciaDv; 
            } 
            set 
            {
                this.agenciaDv = value;
                onPropertyChanged("AgenciaDv");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("conta")]
        public string Conta 
        { 
            get 
            {
                return this.conta; 
            } 
            set 
            {
                this.conta = value;
                onPropertyChanged("Conta");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("conta_dv")]
        public string ContaDv 
        { 
            get 
            {
                return this.contaDv; 
            } 
            set 
            {
                this.contaDv = value;
                onPropertyChanged("ContaDv");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("document_number")]
        public string DocumentNumber 
        { 
            get 
            {
                return this.documentNumber; 
            } 
            set 
            {
                this.documentNumber = value;
                onPropertyChanged("DocumentNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("legal_name")]
        public string LegalName 
        { 
            get 
            {
                return this.legalName; 
            } 
            set 
            {
                this.legalName = value;
                onPropertyChanged("LegalName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("charge_transfer_fees")]
        public bool ChargeTransferFees 
        { 
            get 
            {
                return this.chargeTransferFees; 
            } 
            set 
            {
                this.chargeTransferFees = value;
                onPropertyChanged("ChargeTransferFees");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated 
        { 
            get 
            {
                return this.dateCreated; 
            } 
            set 
            {
                this.dateCreated = value;
                onPropertyChanged("DateCreated");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pix_key")]
        public string PixKey 
        { 
            get 
            {
                return this.pixKey; 
            } 
            set 
            {
                this.pixKey = value;
                onPropertyChanged("PixKey");
            }
        }
    }
} 