/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class CaptureTransaction : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? amount;
        private List<Models.SplitRule> splitRules;
        private Dictionary<string, string> metadata;
        private bool? masync;
        private string apiKey;

        /// <summary>
        /// Valor a ser capturado. Deve ser passado em centavos. Ex: R$ 10.00 = 1000.
        /// </summary>
        [JsonProperty("amount")]
        public int? Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// Regras de divisão da transação.
        /// </summary>
        [JsonProperty("split_rules")]
        public List<Models.SplitRule> SplitRules 
        { 
            get 
            {
                return this.splitRules; 
            } 
            set 
            {
                this.splitRules = value;
                onPropertyChanged("SplitRules");
            }
        }

        /// <summary>
        /// Metadata de informações adicionais, caso queira incluir, i.e: Id do pedido, nome do produto, etc.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata 
        { 
            get 
            {
                return this.metadata; 
            } 
            set 
            {
                this.metadata = value;
                onPropertyChanged("Metadata");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("async")]
        public bool? Async 
        { 
            get 
            {
                return this.masync; 
            } 
            set 
            {
                this.masync = value;
                onPropertyChanged("Async");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }
    }
} 