/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class CreateWithdraw : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int amount;
        private string recipientId;
        private Dictionary<string, string> metadata;
        private string apiKey;

        /// <summary>
        /// Valor, em centavos, a ser transferido para uma determinada conta bancária
        /// </summary>
        [JsonProperty("amount")]
        public int Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// Indica que o valor da transferência sairá da conta do recebedor identificado por este parâmetro. OBS: Caso o recipient_id seja passado, não é necessário passar bank_account_id
        /// </summary>
        [JsonProperty("recipient_id")]
        public string RecipientId 
        { 
            get 
            {
                return this.recipientId; 
            } 
            set 
            {
                this.recipientId = value;
                onPropertyChanged("RecipientId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata 
        { 
            get 
            {
                return this.metadata; 
            } 
            set 
            {
                this.metadata = value;
                onPropertyChanged("Metadata");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }
    }
} 