/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class CreateTransfer : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int amount;
        private string sourceId;
        private string targetId;
        private Dictionary<string, string> metadata;
        private string apiKey;

        /// <summary>
        /// valor em centavos à ser transferido do recebedor fonte (source) para o recebedor alvo (target).
        /// </summary>
        [JsonProperty("amount")]
        public int Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// ID do recebedor fonte, ou seja, de onde o valor será extraído para ser transferido.
        /// </summary>
        [JsonProperty("source_id")]
        public string SourceId 
        { 
            get 
            {
                return this.sourceId; 
            } 
            set 
            {
                this.sourceId = value;
                onPropertyChanged("SourceId");
            }
        }

        /// <summary>
        /// ID do recebedor alvo, ou seja, quem recebe o valor transferido.
        /// </summary>
        [JsonProperty("target_id")]
        public string TargetId 
        { 
            get 
            {
                return this.targetId; 
            } 
            set 
            {
                this.targetId = value;
                onPropertyChanged("TargetId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata 
        { 
            get 
            {
                return this.metadata; 
            } 
            set 
            {
                this.metadata = value;
                onPropertyChanged("Metadata");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }
    }
} 