/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class GetBalance : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.BalanceAmount waitingFunds;
        private Models.BalanceAmount available;
        private Models.BalanceAmount transferred;
        private string apiKey;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("waiting_funds")]
        public Models.BalanceAmount WaitingFunds 
        { 
            get 
            {
                return this.waitingFunds; 
            } 
            set 
            {
                this.waitingFunds = value;
                onPropertyChanged("WaitingFunds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("available")]
        public Models.BalanceAmount Available 
        { 
            get 
            {
                return this.available; 
            } 
            set 
            {
                this.available = value;
                onPropertyChanged("Available");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("transferred")]
        public Models.BalanceAmount Transferred 
        { 
            get 
            {
                return this.transferred; 
            } 
            set 
            {
                this.transferred = value;
                onPropertyChanged("Transferred");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }
    }
} 