/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class Payment : BaseModel 
    {
        // These fields hold the values for the public properties.
        private DateTime? paymentDate;
        private int netAmount;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("payment_date")]
        public DateTime? PaymentDate 
        { 
            get 
            {
                return this.paymentDate; 
            } 
            set 
            {
                this.paymentDate = value;
                onPropertyChanged("PaymentDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("net_amount")]
        public int NetAmount 
        { 
            get 
            {
                return this.netAmount; 
            } 
            set 
            {
                this.netAmount = value;
                onPropertyChanged("NetAmount");
            }
        }
    }
} 