/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class RefundTransaction : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? amount;
        private List<Models.RefundTransactionSplitRule> splitRules;
        private bool? masync;
        private string apiKey;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public int? Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// The refund split rules list
        /// </summary>
        [JsonProperty("split_rules")]
        public List<Models.RefundTransactionSplitRule> SplitRules 
        { 
            get 
            {
                return this.splitRules; 
            } 
            set 
            {
                this.splitRules = value;
                onPropertyChanged("SplitRules");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("async")]
        public bool? Async 
        { 
            get 
            {
                return this.masync; 
            } 
            set 
            {
                this.masync = value;
                onPropertyChanged("Async");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("api_key")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }
    }
} 