/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class RefundTransactionSplitRule : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private string recipientId;
        private int? amount;
        private int? percentage;
        private bool chargeProcessingFee;

        /// <summary>
        /// The split rule identifier
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Recipient Identifier
        /// </summary>
        [JsonProperty("recipient_id")]
        public string RecipientId 
        { 
            get 
            {
                return this.recipientId; 
            } 
            set 
            {
                this.recipientId = value;
                onPropertyChanged("RecipientId");
            }
        }

        /// <summary>
        /// Split rule amount value
        /// </summary>
        [JsonProperty("amount")]
        public int? Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// Split rule amount percentage value
        /// </summary>
        [JsonProperty("percentage")]
        public int? Percentage 
        { 
            get 
            {
                return this.percentage; 
            } 
            set 
            {
                this.percentage = value;
                onPropertyChanged("Percentage");
            }
        }

        /// <summary>
        /// Toggle the fee's payer in case of refund
        /// </summary>
        [JsonProperty("charge_processing_fee")]
        public bool ChargeProcessingFee 
        { 
            get 
            {
                return this.chargeProcessingFee; 
            } 
            set 
            {
                this.chargeProcessingFee = value;
                onPropertyChanged("ChargeProcessingFee");
            }
        }
    }
} 