/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class RegisterInformation : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string type;
        private string documentNumber;
        private string name;
        private string siteUrl;
        private string email;
        private List<Models.Phone> phoneNumbers;
        private List<Models.ManagingPartner> managingPartners;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type")]
        public string Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("document_number")]
        public string DocumentNumber 
        { 
            get 
            {
                return this.documentNumber; 
            } 
            set 
            {
                this.documentNumber = value;
                onPropertyChanged("DocumentNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("site_url")]
        public string SiteUrl 
        { 
            get 
            {
                return this.siteUrl; 
            } 
            set 
            {
                this.siteUrl = value;
                onPropertyChanged("SiteUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("phone_numbers")]
        public List<Models.Phone> PhoneNumbers 
        { 
            get 
            {
                return this.phoneNumbers; 
            } 
            set 
            {
                this.phoneNumbers = value;
                onPropertyChanged("PhoneNumbers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("managing_partners")]
        public List<Models.ManagingPartner> ManagingPartners 
        { 
            get 
            {
                return this.managingPartners; 
            } 
            set 
            {
                this.managingPartners = value;
                onPropertyChanged("ManagingPartners");
            }
        }
    }
} 