/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class Shipping : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private int? fee;
        private DateTime? deliveryDate;
        private Models.Address address;
        private int? id;
        private bool? expedited;

        /// <summary>
        /// Obrigatório. Nome da entidade de cobrança
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Obrigatório. Taxa de envio cobrada do comprador. Por exemplo, se a taxa de envio é de dez reais e três centavos (R$10,03), o valor deve ser fornecido como ‘1003’
        /// </summary>
        [JsonProperty("fee")]
        public int? Fee 
        { 
            get 
            {
                return this.fee; 
            } 
            set 
            {
                this.fee = value;
                onPropertyChanged("Fee");
            }
        }

        /// <summary>
        /// Data de entrega. Estimativa fornecida no formato AAAA-MM-DD
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("delivery_date")]
        public DateTime? DeliveryDate 
        { 
            get 
            {
                return this.deliveryDate; 
            } 
            set 
            {
                this.deliveryDate = value;
                onPropertyChanged("DeliveryDate");
            }
        }

        /// <summary>
        /// Obrigatório. Dados do endereço de envio. Objeto descrito aqui.
        /// </summary>
        [JsonProperty("address")]
        public Models.Address Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Entrega expressa. Se for entrega expressa, deve conter ‘true’ (sim). Caso contrário, deve conter ‘false’ (não)
        /// </summary>
        [JsonProperty("expedited")]
        public bool? Expedited 
        { 
            get 
            {
                return this.expedited; 
            } 
            set 
            {
                this.expedited = value;
                onPropertyChanged("Expedited");
            }
        }
    }
} 