/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;


namespace PagarmeAPI.Standard.Models
{
    public class Transaction : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.TransactionStatus status;
        private string refuseReason;
        private string statusReason;
        private string acquirerResponseCode;
        private string acquirerName;
        private string acquirerId;
        private string softDescriptor;
        private int? tid;
        private int? nsu;
        private DateTime dateCreated;
        private DateTime dateUpdated;
        private int amount;
        private int authorizedAmount;
        private int paidAmount;
        private int refundedAmount;
        private int installments;
        private int? id;
        private double cost;
        private string cardHolderName;
        private string cardLastDigits;
        private string cardFirstDigits;
        private string cardBrand;
        private string cardPinMode;
        private bool cardMagstripeFallback;
        private string postbackUrl;
        private Models.PaymentMethod paymentMethod;
        private string captureMethod;
        private int? antifraudScore;
        private string boletoUrl;
        private string boletoBarcode;
        private DateTime? boletoExpirationDate;
        private string referer;
        private string ip;
        private string subscriptionId;
        private string phone;
        private Models.Address address;
        private Models.Customer customer;
        private Models.Billing billing;
        private List<Models.TransactionItem> items;
        private Dictionary<string, string> metadata;
        private object antifraudMetadata;
        private string referenceKey;
        private Models.Card card;
        private List<Models.SplitRule> splitRules;
        private string authorizationCode;
        private string device;
        private string localTransactionId;
        private string localTime;
        private bool fraudCovered;
        private string orderId;
        private string riskLevel;
        private string receiptUrl;
        private Models.Payment payment;
        private string addition;
        private string discount;
        private Models.PrivateLabel privateLabel;
        private List<Models.PixAdditionalFields> pixAdditionalFields;
        private DateTime? pixExpirationDate;
        private string pixQrCode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.TransactionStatus Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("refuse_reason")]
        public string RefuseReason 
        { 
            get 
            {
                return this.refuseReason; 
            } 
            set 
            {
                this.refuseReason = value;
                onPropertyChanged("RefuseReason");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status_reason")]
        public string StatusReason 
        { 
            get 
            {
                return this.statusReason; 
            } 
            set 
            {
                this.statusReason = value;
                onPropertyChanged("StatusReason");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("acquirer_response_code")]
        public string AcquirerResponseCode 
        { 
            get 
            {
                return this.acquirerResponseCode; 
            } 
            set 
            {
                this.acquirerResponseCode = value;
                onPropertyChanged("AcquirerResponseCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("acquirer_name")]
        public string AcquirerName 
        { 
            get 
            {
                return this.acquirerName; 
            } 
            set 
            {
                this.acquirerName = value;
                onPropertyChanged("AcquirerName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("acquirer_id")]
        public string AcquirerId 
        { 
            get 
            {
                return this.acquirerId; 
            } 
            set 
            {
                this.acquirerId = value;
                onPropertyChanged("AcquirerId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("soft_descriptor")]
        public string SoftDescriptor 
        { 
            get 
            {
                return this.softDescriptor; 
            } 
            set 
            {
                this.softDescriptor = value;
                onPropertyChanged("SoftDescriptor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("tid")]
        public int? Tid 
        { 
            get 
            {
                return this.tid; 
            } 
            set 
            {
                this.tid = value;
                onPropertyChanged("Tid");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nsu")]
        public int? Nsu 
        { 
            get 
            {
                return this.nsu; 
            } 
            set 
            {
                this.nsu = value;
                onPropertyChanged("Nsu");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime DateCreated 
        { 
            get 
            {
                return this.dateCreated; 
            } 
            set 
            {
                this.dateCreated = value;
                onPropertyChanged("DateCreated");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime DateUpdated 
        { 
            get 
            {
                return this.dateUpdated; 
            } 
            set 
            {
                this.dateUpdated = value;
                onPropertyChanged("DateUpdated");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount")]
        public int Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("authorized_amount")]
        public int AuthorizedAmount 
        { 
            get 
            {
                return this.authorizedAmount; 
            } 
            set 
            {
                this.authorizedAmount = value;
                onPropertyChanged("AuthorizedAmount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paid_amount")]
        public int PaidAmount 
        { 
            get 
            {
                return this.paidAmount; 
            } 
            set 
            {
                this.paidAmount = value;
                onPropertyChanged("PaidAmount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("refunded_amount")]
        public int RefundedAmount 
        { 
            get 
            {
                return this.refundedAmount; 
            } 
            set 
            {
                this.refundedAmount = value;
                onPropertyChanged("RefundedAmount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("installments")]
        public int Installments 
        { 
            get 
            {
                return this.installments; 
            } 
            set 
            {
                this.installments = value;
                onPropertyChanged("Installments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cost")]
        public double Cost 
        { 
            get 
            {
                return this.cost; 
            } 
            set 
            {
                this.cost = value;
                onPropertyChanged("Cost");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card_holder_name")]
        public string CardHolderName 
        { 
            get 
            {
                return this.cardHolderName; 
            } 
            set 
            {
                this.cardHolderName = value;
                onPropertyChanged("CardHolderName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card_last_digits")]
        public string CardLastDigits 
        { 
            get 
            {
                return this.cardLastDigits; 
            } 
            set 
            {
                this.cardLastDigits = value;
                onPropertyChanged("CardLastDigits");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card_first_digits")]
        public string CardFirstDigits 
        { 
            get 
            {
                return this.cardFirstDigits; 
            } 
            set 
            {
                this.cardFirstDigits = value;
                onPropertyChanged("CardFirstDigits");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card_brand")]
        public string CardBrand 
        { 
            get 
            {
                return this.cardBrand; 
            } 
            set 
            {
                this.cardBrand = value;
                onPropertyChanged("CardBrand");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card_pin_mode")]
        public string CardPinMode 
        { 
            get 
            {
                return this.cardPinMode; 
            } 
            set 
            {
                this.cardPinMode = value;
                onPropertyChanged("CardPinMode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card_magstripe_fallback")]
        public bool CardMagstripeFallback 
        { 
            get 
            {
                return this.cardMagstripeFallback; 
            } 
            set 
            {
                this.cardMagstripeFallback = value;
                onPropertyChanged("CardMagstripeFallback");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postback_url")]
        public string PostbackUrl 
        { 
            get 
            {
                return this.postbackUrl; 
            } 
            set 
            {
                this.postbackUrl = value;
                onPropertyChanged("PostbackUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("payment_method", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.PaymentMethod PaymentMethod 
        { 
            get 
            {
                return this.paymentMethod; 
            } 
            set 
            {
                this.paymentMethod = value;
                onPropertyChanged("PaymentMethod");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("capture_method")]
        public string CaptureMethod 
        { 
            get 
            {
                return this.captureMethod; 
            } 
            set 
            {
                this.captureMethod = value;
                onPropertyChanged("CaptureMethod");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("antifraud_score")]
        public int? AntifraudScore 
        { 
            get 
            {
                return this.antifraudScore; 
            } 
            set 
            {
                this.antifraudScore = value;
                onPropertyChanged("AntifraudScore");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("boleto_url")]
        public string BoletoUrl 
        { 
            get 
            {
                return this.boletoUrl; 
            } 
            set 
            {
                this.boletoUrl = value;
                onPropertyChanged("BoletoUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("boleto_barcode")]
        public string BoletoBarcode 
        { 
            get 
            {
                return this.boletoBarcode; 
            } 
            set 
            {
                this.boletoBarcode = value;
                onPropertyChanged("BoletoBarcode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("boleto_expiration_date")]
        public DateTime? BoletoExpirationDate 
        { 
            get 
            {
                return this.boletoExpirationDate; 
            } 
            set 
            {
                this.boletoExpirationDate = value;
                onPropertyChanged("BoletoExpirationDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("referer")]
        public string Referer 
        { 
            get 
            {
                return this.referer; 
            } 
            set 
            {
                this.referer = value;
                onPropertyChanged("Referer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ip")]
        public string Ip 
        { 
            get 
            {
                return this.ip; 
            } 
            set 
            {
                this.ip = value;
                onPropertyChanged("Ip");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subscription_id")]
        public string SubscriptionId 
        { 
            get 
            {
                return this.subscriptionId; 
            } 
            set 
            {
                this.subscriptionId = value;
                onPropertyChanged("SubscriptionId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("phone")]
        public string Phone 
        { 
            get 
            {
                return this.phone; 
            } 
            set 
            {
                this.phone = value;
                onPropertyChanged("Phone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("address")]
        public Models.Address Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customer")]
        public Models.Customer Customer 
        { 
            get 
            {
                return this.customer; 
            } 
            set 
            {
                this.customer = value;
                onPropertyChanged("Customer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("billing")]
        public Models.Billing Billing 
        { 
            get 
            {
                return this.billing; 
            } 
            set 
            {
                this.billing = value;
                onPropertyChanged("Billing");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("items")]
        public List<Models.TransactionItem> Items 
        { 
            get 
            {
                return this.items; 
            } 
            set 
            {
                this.items = value;
                onPropertyChanged("Items");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata 
        { 
            get 
            {
                return this.metadata; 
            } 
            set 
            {
                this.metadata = value;
                onPropertyChanged("Metadata");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("antifraud_metadata")]
        public object AntifraudMetadata 
        { 
            get 
            {
                return this.antifraudMetadata; 
            } 
            set 
            {
                this.antifraudMetadata = value;
                onPropertyChanged("AntifraudMetadata");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("reference_key")]
        public string ReferenceKey 
        { 
            get 
            {
                return this.referenceKey; 
            } 
            set 
            {
                this.referenceKey = value;
                onPropertyChanged("ReferenceKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("card")]
        public Models.Card Card 
        { 
            get 
            {
                return this.card; 
            } 
            set 
            {
                this.card = value;
                onPropertyChanged("Card");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("split_rules")]
        public List<Models.SplitRule> SplitRules 
        { 
            get 
            {
                return this.splitRules; 
            } 
            set 
            {
                this.splitRules = value;
                onPropertyChanged("SplitRules");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("authorization_code")]
        public string AuthorizationCode 
        { 
            get 
            {
                return this.authorizationCode; 
            } 
            set 
            {
                this.authorizationCode = value;
                onPropertyChanged("AuthorizationCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("device")]
        public string Device 
        { 
            get 
            {
                return this.device; 
            } 
            set 
            {
                this.device = value;
                onPropertyChanged("Device");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("local_transaction_id")]
        public string LocalTransactionId 
        { 
            get 
            {
                return this.localTransactionId; 
            } 
            set 
            {
                this.localTransactionId = value;
                onPropertyChanged("LocalTransactionId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("local_time")]
        public string LocalTime 
        { 
            get 
            {
                return this.localTime; 
            } 
            set 
            {
                this.localTime = value;
                onPropertyChanged("LocalTime");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fraud_covered")]
        public bool FraudCovered 
        { 
            get 
            {
                return this.fraudCovered; 
            } 
            set 
            {
                this.fraudCovered = value;
                onPropertyChanged("FraudCovered");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("order_id")]
        public string OrderId 
        { 
            get 
            {
                return this.orderId; 
            } 
            set 
            {
                this.orderId = value;
                onPropertyChanged("OrderId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("risk_level")]
        public string RiskLevel 
        { 
            get 
            {
                return this.riskLevel; 
            } 
            set 
            {
                this.riskLevel = value;
                onPropertyChanged("RiskLevel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("receipt_url")]
        public string ReceiptUrl 
        { 
            get 
            {
                return this.receiptUrl; 
            } 
            set 
            {
                this.receiptUrl = value;
                onPropertyChanged("ReceiptUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("payment")]
        public Models.Payment Payment 
        { 
            get 
            {
                return this.payment; 
            } 
            set 
            {
                this.payment = value;
                onPropertyChanged("Payment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("addition")]
        public string Addition 
        { 
            get 
            {
                return this.addition; 
            } 
            set 
            {
                this.addition = value;
                onPropertyChanged("Addition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("discount")]
        public string Discount 
        { 
            get 
            {
                return this.discount; 
            } 
            set 
            {
                this.discount = value;
                onPropertyChanged("Discount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("private_label")]
        public Models.PrivateLabel PrivateLabel 
        { 
            get 
            {
                return this.privateLabel; 
            } 
            set 
            {
                this.privateLabel = value;
                onPropertyChanged("PrivateLabel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pix_additional_fields")]
        public List<Models.PixAdditionalFields> PixAdditionalFields 
        { 
            get 
            {
                return this.pixAdditionalFields; 
            } 
            set 
            {
                this.pixAdditionalFields = value;
                onPropertyChanged("PixAdditionalFields");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("pix_expiration_date")]
        public DateTime? PixExpirationDate 
        { 
            get 
            {
                return this.pixExpirationDate; 
            } 
            set 
            {
                this.pixExpirationDate = value;
                onPropertyChanged("PixExpirationDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pix_qr_code")]
        public string PixQrCode 
        { 
            get 
            {
                return this.pixQrCode; 
            } 
            set 
            {
                this.pixQrCode = value;
                onPropertyChanged("PixQrCode");
            }
        }
    }
} 