/*
 * PagarmeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using APIMATIC.SDK.Common;

namespace PagarmeAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum TransferStatus
    {
        PENDING_TRANSFER, //TODO: Write general description for this method
        TRANSFERRED, //TODO: Write general description for this method
        FAILED, //TODO: Write general description for this method
        PROCESSING, //TODO: Write general description for this method
        CANCELED, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type TransferStatus
    /// </summary>
    public static class TransferStatusHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "pending_transfer", "transferred", "failed", "processing", "canceled" };

        /// <summary>
        /// Converts a TransferStatus value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The TransferStatus value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(TransferStatus enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case TransferStatus.PENDING_TRANSFER:
                case TransferStatus.TRANSFERRED:
                case TransferStatus.FAILED:
                case TransferStatus.PROCESSING:
                case TransferStatus.CANCELED:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of TransferStatus values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of TransferStatus values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<TransferStatus> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into TransferStatus value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed TransferStatus value</returns>
        public static TransferStatus ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type TransferStatus", value));

            return (TransferStatus) index;
        }
    }
} 