/*
 * PagarmeCoreApi.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using PagarmeCoreApi.Standard;
using PagarmeCoreApi.Standard.Utilities; 
using PagarmeCoreApi.Standard.Http.Client;
using PagarmeCoreApi.Standard.Http.Response;
using PagarmeCoreApi.Tests.Helpers;
using NUnit.Framework;
using PagarmeCoreApi.Standard;
using PagarmeCoreApi.Standard.Controllers;
using PagarmeCoreApi.Standard.Exceptions;

namespace PagarmeCoreApi.Tests
{
    [TestFixture]
    public class RecipientsControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static IRecipientsController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Recipients;
        }

        /// <summary>
        /// Retrieves paginated recipients information 
        /// </summary>
        [Test]
        public async Task TestTestGetRecipients() 
        {
            // Parameters for the API call
            int? page = null;
            int? size = null;

            // Perform API call
            Standard.Models.ListRecipientResponse result = null;

            try
            {
                result = await controller.GetRecipientsAsync(page, size);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

        /// <summary>
        /// GetDefaultRecipient 
        /// </summary>
        [Test]
        public async Task TestTestGetDefaultRecipient() 
        {

            // Perform API call
            Standard.Models.GetRecipientResponse result = null;

            try
            {
                result = await controller.GetDefaultRecipientAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

    }
}